### ISSUE TITLE
Ability to collapse or expand sections

### ISSUE THREAD

**Issue by MikeDeasyBB** [GingerBear/json-viewer#9]
Can you add a '+' or '-' to each section so I can collapse or expand it?

**Comment by GingerBear** [comment]
good suggestion, I think I can add that

**Comment by Qiki** [comment]
😕

**Comment by GingerBear** [comment]
@Qiki  you want to add this feature?

**Comment by Qiki** [comment]
@GingerBear no, sorry, i don't.

**Comment by GingerBear** [comment]
added to the new release https://github.com/GingerBear/json-viewer/releases

**Comment by Qiki** [comment]
🎆 🍾 💃

**Comment by MikeDeasyBB** [comment]
Thanks Neil
